name: alphabet_list_view
description: A scrollable list with sidebar
version: 0.1.0

publish_to: 'none'

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_sticky_header: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  dart_code_metrics: ^4.8.1

flutter:
